# Generated by Django 2.2.16 on 2022-08-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220827_0608'),
        ('reviews', '0005_auto_20220826_1306'),
    ]

    operations = [
    ]
